<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>7f632a13-dcc3-4194-ab2d-8e36dba86aa8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GincanaHud.Api\GincanaHud.Api.csproj" />
    <ProjectReference Include="..\GincanaHud.Admin\GincanaHud.Admin.csproj" />
  </ItemGroup>

</Project>
