@GincanaHud.Api_HostAddress = http://localhost:5263

GET {{GincanaHud.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{GincanaHud.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
